package com.greendao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.konsung.bean.MeasureDataBean;
import com.konsung.bean.PatientBean;
import com.konsung.bean.UserBean;

import com.greendao.dao.MeasureDataBeanDao;
import com.greendao.dao.PatientBeanDao;
import com.greendao.dao.UserBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig measureDataBeanDaoConfig;
    private final DaoConfig patientBeanDaoConfig;
    private final DaoConfig userBeanDaoConfig;

    private final MeasureDataBeanDao measureDataBeanDao;
    private final PatientBeanDao patientBeanDao;
    private final UserBeanDao userBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        measureDataBeanDaoConfig = daoConfigMap.get(MeasureDataBeanDao.class).clone();
        measureDataBeanDaoConfig.initIdentityScope(type);

        patientBeanDaoConfig = daoConfigMap.get(PatientBeanDao.class).clone();
        patientBeanDaoConfig.initIdentityScope(type);

        userBeanDaoConfig = daoConfigMap.get(UserBeanDao.class).clone();
        userBeanDaoConfig.initIdentityScope(type);

        measureDataBeanDao = new MeasureDataBeanDao(measureDataBeanDaoConfig, this);
        patientBeanDao = new PatientBeanDao(patientBeanDaoConfig, this);
        userBeanDao = new UserBeanDao(userBeanDaoConfig, this);

        registerDao(MeasureDataBean.class, measureDataBeanDao);
        registerDao(PatientBean.class, patientBeanDao);
        registerDao(UserBean.class, userBeanDao);
    }
    
    public void clear() {
        measureDataBeanDaoConfig.clearIdentityScope();
        patientBeanDaoConfig.clearIdentityScope();
        userBeanDaoConfig.clearIdentityScope();
    }

    public MeasureDataBeanDao getMeasureDataBeanDao() {
        return measureDataBeanDao;
    }

    public PatientBeanDao getPatientBeanDao() {
        return patientBeanDao;
    }

    public UserBeanDao getUserBeanDao() {
        return userBeanDao;
    }

}
